### ISSUE TITLE
Probably ought to exclude GIF Plays Pokemon

### ISSUE THREAD

**Issue by lunasorcery** [cpsdqs/cohost-dl#10]
At present, [this post](https://cohost.org/hell-labs/post/61337-gif-plays-pkmn-blue) will cause the downloader to get stuck - it'll download all the button images causing spurious inputs on the bot, and then get stuck downloading the infinitely-streaming screen.gif. Maybe the downloader could avoid fetching anything hosted at eggbugpocket.queertra.sh:15171 ?

**Comment by c-probably-archived20260718** [comment]
there’s several posts like that! that’s what `DO_NOT_FETCH_HOSTNAMES` is for. I suppose it could be in there as the default example, since it’s popular
