### ISSUE TITLE
getting "no file or directory found" error when building post-index for my own page

### ISSUE THREAD

**Issue by wowperfect** [cpsdqs/cohost-dl#13]
<img width="1218" alt="image" src="https://github.com/user-attachments/assets/d73e62fe-5d86-444e-91f2-170e39104af9">

I am getting this error and I'm not sure how to fix it... it is true that the out/duck-cunt/post directory doesn't exist but I'm not sure why it wasn't made

<img width="619" alt="image" src="https://github.com/user-attachments/assets/734e5a2a-2854-44eb-8fcf-5c00c4dc8489">

here is the start of my list of projects in CONFIG.ts

**Comment by c-probably-archived20260718** [comment]
303ac05 - well, I can add error handling for that, but that wouldn’t fix the underlying error of no posts being loaded for that project… don’t know why that would happen. I suppose you can find out now, since it prints a list of all errors at the end

**Comment by wowperfect** [comment]
I can fetch and re-run and let you know what output I get

**Comment by wowperfect** [comment]
okay possible cause of the bug: on my main acct I have `@duck-cunt` muted so I don't see my own posts from that acct in my feed. could that have caused the issue? I have unmuted it just in case

is there a way to trigger a refetch of those posts? there is an `out/duck-cunt/posts.json`

**Comment by wowperfect** [comment]
this was fixed by unmuting and following my own pages
