### ISSUE TITLE
archive new posts without deleting all old posts

### ISSUE THREAD

**Issue by SArpnt** [cpsdqs/cohost-dl#17]
i ran the script with plenty of data, and since then i've liked more posts and made more posts, but i don't think i have time to rerun the entire thing before some people delete their accounts and i can't keep their posts i liked

i'm not too concerned with how messy the data is as long as i actually have all of it for later, that can be sorted with more programs long after cohost goes down

i would try tweaking the script myself to do this but i can't really figure it out

hell if you can just point me at what file to move and what part of the script i can skip that would be perfectly fine too

**Comment by c-probably-archived20260718** [comment]
deleting the liked.json/posts.json doesn’t delete the files for each post, so if you only need to get your new posts, you can just delete those and run the script again. However, if you want to update the post pages as well without deleting old data… that’ll be quite difficult…

**Comment by c-probably-archived20260718** [comment]
cohost-dl 2 can now merge data from cohost-dl 1 into its database, so every case of this should now be doable
