### ISSUE TITLE
cws don't open when clicked

### ISSUE THREAD

**Issue by atomicthumbs** [cpsdqs/cohost-dl#2]
something that postprocesses the html might be helpful so people don't have to download all it again.

i know you know about this one but i am putting it in an issue in the hopes it is helpful

**Comment by NoahTheDuke** [comment]
related, images under CWs don't seem to be downloaded, as the `img` html nodes haven't been loaded/created yet.

**Comment by c-probably-archived20260718** [comment]
see #3. same resolution
