### ISSUE TITLE
module not found?

### ISSUE THREAD

**Issue by frecklenog** [cpsdqs/cohost-dl#21]
hi! i'm from the "how to run cohost-dl on microsoft windows for non-programmers" guide. i've set everything up in CONFIG.ts (which. turned into a .txt when i edited it in notepad. not sure if that's supposed to happen, but i can't find a way to save it as anything other than various kinds of text docs?), but when i try to run deno (` deno run ... main.ts`), i get an error that says 
`error: Module not found "file:///F:/cohost%20export/cohost-dl-main/CONFIG.ts".
     at file:///F:/cohost%20export/cohost-dl-main/src/config.ts:1:23`
i have. no idea what i'm doing wrong. 
![image](https://github.com/user-attachments/assets/6caac407-8bac-4a78-8d2b-948c6c50774c)

**Comment by c-probably-archived20260718** [comment]
If you mean it turned into a TXT file, that isn’t supposed to happen. That would also explain why the file cannot be found. I suppose that if there’s no other way, you can try the `mv CONFIG.ts.txt CONFIG.ts` (or maybe `mv CONFIG.txt CONFIG.ts` or whatever it’s been saved as) command in PowerShell to force it

**Comment by frecklenog** [comment]
hooray it works now !! thank you :]

**Comment by c-probably-archived20260718** [comment]
ok! closing as resolved
