### ISSUE TITLE
Posts Out of Order

### ISSUE THREAD

**Issue by mieffika** [cpsdqs/cohost-dl#23]
My very last few posts show up out of order, though the timestamps seem correct.  Is there a place where I can change the order of the post IDs around to get them to show up correctly?  I tried in index.html but that didn't seem to do anything, even with a forced cache reload.

**Comment by c-probably-archived20260718** [comment]
oh… it seems I’m ordering posts by ID instead of by date, which means that if you made drafts and posted them later, they probably show up out of order. This is an issue in the cdl-chunk~*.js data, so I’ll see if I can’t fix it in code later today

**Comment by c-probably-archived20260718** [comment]
fixed in d6f6140. you can just run the new version on the same out directory and it’ll fix itself
