### ISSUE TITLE
cdl2: illegal path characters not handled on Windows

### ISSUE THREAD

**Issue by G-F-D** [cpsdqs/cohost-dl#26]
`?` and `:` (among others, but these are the ones coming up in practice for me) are forbidden in filenames and directories on Microsoft Windows, and cdl2 does not seem to anticipate this when downloading resource files, nor handle it gracefully. Failing to save the resource locally because of an OS error does not abort the download, but instead results in fruitless retries, which stalls the whole process in addition to generating needless requests. cdl1 did not seem to have this issue.

A couple examples (with some redactions):
```
[INFO  cohost_dl::dl] try 4 for https://pbs.twimg.com/media/XXXXXXXX?format=jpg: waiting for 4.83s before continuing to be polite
[ERROR cohost_dl::dl] resource for post XXXXXXX: The filename, directory name, or volume label syntax is incorrect. (os error 123)
```
```
[INFO  cohost_dl::dl] try 4 for https://proxy-staging.cohostcdn.org/XXXXXXXX/f:png/XXXXXXXX: waiting for 4.83s before continuing to be polite
[ERROR cohost_dl::dl] resource for post XXXXXXX: getting relative path
```

(Thank you for all your work on this, and for making it open source!)

**Comment by c-probably-archived20260718** [comment]
yeah, cdl1 does handle this, and I still haven’t gotten around to testing windows for this one
