### ISSUE TITLE
modification of the config for specific use 

### ISSUE THREAD

**Issue by SoftDemon7** [cpsdqs/cohost-dl#31]
Hello! I have a problem: I want to download the profile data of @staff, but I can't do it. Subscriptions, likes and other functions are currently disabled on the site, so I can neither subscribe to @staff, nor use archiving. How can I download the data of this profile under such conditions? I tried to figure it out, but the problem is that I am not subscribed, which means I can't download it. Maybe there is a way to change the config so that I can download specific profiles?

**Comment by c-probably-archived20260718** [comment]
if you are using cohost-dl 1 (deno):
```js
export const PROJECTS = [
  'theres-probably-some-other-stuff-already-here',
  'staff',
];
```

if you are using cohost-dl 2 (binary):
```toml
load_profile_posts = [
  'theres-probably-some-other-stuff-already-here',
  'staff',
]
```

This will download every post from staff, which I think is what you want?

**Comment by SoftDemon7** [comment]
yes it really works thanks in my code there was a problem that I used 
load_profile_posts = ["all","staff"]
need to use ['all','staff']
