### ISSUE TITLE
Downloading fails ungracefully if list of pages to download contains a non-followed private page

### ISSUE THREAD

**Issue by atomicthumbs** [cpsdqs/cohost-dl#34]
it tries ten times to load trpc/posts.profilePosts, receives a 500 each time, and then fails, halting the download process and necessitating manual config editing.

**Comment by c-probably-archived20260718** [comment]
not sure what could be done about this. nothing about the error specifies its cause as being profile privacy :/

and, uh, I can’t find any sort of api for figuring out whether you’re allowed to read someone’s profile

**Comment by atomicthumbs** [comment]
the ideal for what i'm doing would be to just skip that page instead of halting the entire process

**Comment by c-probably-archived20260718** [comment]
it’s a new day… found some time & had a look at how cohost does it. you can now use a secret additional option:
```toml
skip_inaccessible_profiles = true
```
and it’ll just print an error instead of dying slowly

(sorry this took so long… it’s been A Month)
