### ISSUE TITLE
error trying to log in with email+password OR session cookie (wine)

### ISSUE THREAD

**Issue by JPLeBreton** [cpsdqs/cohost-dl#35]
Using the windows EXE on this page: https://cloudwithlightning.net/random/chostin/cohost-dl

I specify a data path and media download directory, and then try to log in. Giving my email and password give this error:
```
Logging in...
Error: error sending request for url (https://cohost.org/rc/login)
Caused by:
    0: client error (Connect)
    1: OS Error -2146762482 (FormatMessageW() returned error 317) (os error -2146762482)
```

Trying with session cookie gives this error:

```
Checking...
[2024-11-11T02:55:38Z ERROR cohost_dl::context] GET https://cohost.org/api/v1/trpc/login.loggedIn: error sending request for 
url (https://cohost.org/api/v1/trpc/login.loggedIn). trying again (try 2/10)
```

I'm running via Wine on Linux. Is this an issue on my end, or cohost's?

**Comment by SArpnt** [comment]
considering it's an os error on a windows function i'm thinking it's some issue with wine. you can still compile from source, i've done this and it works fine. you need to install npm and rust, and follow the instructions [here](https://github.com/cpsdqs/cohost-dl/blob/main/db/README.md)

**Comment by JPLeBreton** [comment]
I'll give it a shot. I was just looking to avoid that because the first line under that section says
> compile the post & markdown renderer. this is super jank. it currently requires running cohost-dl 1 as well

**Comment by JPLeBreton** [comment]
I was able to run the EXE build from a windows machine, and it worked fine. So this problem appears to be Wine + Linux related. Feel free to close if supporting that is outside the scope of this program.

**Comment by c-probably-archived20260718** [comment]
I don’t think I will be supporting wine. Linux is technically supported, I just can’t figure out how to make a binary that runs on more than just my computer :v
and, well, the janky parts of the build process are because I can’t really put cohost source code in this repo…
