### ISSUE TITLE
random failure on downloading some pages (v2)

### ISSUE THREAD

**Issue by mrkranston** [cpsdqs/cohost-dl#38]
i'm attempting to do a full timeline download, but for some reason the program will just give up on downloading some pages.
`⠄ @Keeble page 10 (173 posts) ← adding post 19/20 (ID 5374666)`
`⠤ @Keeble page 10 (173 posts) ← adding post 19/20 (ID 5374666)`
`[2024-12-14T14:44:21Z ERROR cohost_dl::dl] GET https://cohost.org/api/v1/trpc/posts.profilePosts?input=%7B%22projectHand
le%22%3A%22Keeble%22%2C%22page%22%3A10%2C%22options%22%3A%7B%22hideAsks%22%3Afalse%2C%22hideReplies%22%3Afalse%2C%22hide
Shares%22%3Afalse%2C%22pinnedPostsAtTop%22%3Atrue%2C%22viewingOnProjectPage%22%3Atrue%7D%7D: error sending request for url (https://cohost.org/api/v1/trpc/posts.profilePosts?input=%7B%22projectHandle%22%3A%22Keeble%22%2C%22page%22%3A10%2C%2
2options%22%3A%7B%22hideAsks%22%3Afalse%2C%22hideReplies%22%3Afalse%2C%22hideShares%22%3Afalse%2C%22pinnedPostsAtTop%22%
3Atrue%2C%22viewingOnProjectPage%22%3Atrue%7D%7D)`
i'm not sure what the issue could be. there was at least one other page that showed a similar error when i tried to save it, so i skipped that page because i thought it just had a broken post of some kind. but its shown up twice now, so i'm assuming it is a bug. is there any chance there's an easy fix for this? thank you

**Comment by c-probably-archived20260718** [comment]
“error sending request for url” is some kind of vague networking failure, which I don’t think I can do anything about (my ISP does this too, sometimes). It’ll usually go away on try 2 though? I’m pretty sure it should be retrying that request instead of quitting…

**Comment by mrkranston** [comment]
well it worked after trying it this time. it just happened multiple times on the same pages, and it didnt seem like something it should stop for, so i thought it was an issue with the program. thanks for the help, and thanks for making this in the first place
