### ISSUE TITLE
missing import

### ISSUE THREAD

**Issue by NoahTheDuke** [cpsdqs/cohost-dl#7]
https://github.com/cpsdqs/cohost-dl/blob/b24840c40b2da1eccafadcbe472c519f028347bd/main.ts#L8

should this be `from "config.ts"`?

**Comment by c-probably-archived20260718** [comment]
oh, the file was gitignored. sorry! ce2ee4b

**Comment by NoahTheDuke** [comment]
thanks homie, i love this tool
